<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.22000.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishAot>true</PublishAot>
    <StripSymbols>true</StripSymbols>
    <DebugType>None</DebugType>
    <AssemblyName>WuwaAssetExplorer</AssemblyName>
    <RootNamespace>WuwaAssetExplorer.Launcher</RootNamespace>
    <ApplicationIcon>..\WuwaAssetExplorer.App\Assets\AppIcon.ico</ApplicationIcon>
  </PropertyGroup>
</Project>
